# Generated by Django 4.2.11 on 2025-04-21 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='competition_level',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Competitive', 'Competitive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='sport',
            field=models.CharField(max_length=100),
        ),
    ]
